version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!#
    ports:
      - 1433:1433
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  redis_data:
    driver: local
