apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-architecture-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-architecture-app
  template:
    metadata:
      labels:
        app: clean-architecture-app
    spec:
      containers:
      - name: clean-architecture-app
        image: alexdev28/clean-architecture
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: clean-architecture-service
spec:
  selector:
    app: clean-architecture-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Password123!#"
        ports:
        - containerPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: clean-architecture-db-service
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP