name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 1,15 * *" # Every two weeks

jobs:
  updatePackages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x

    - name: Install dotnet-outdated
      run: dotnet tool install --global dotnet-outdated-tool

    - name: Update packages
      id: outdated
      run: |
          outdated=$(dotnet outdated CleanArchitecture.sln -u)
          echo "::set-output name=updates::$outdated"

    - name: Check for changes
      id: changes
      run: git diff --exit-code || echo "::set-output name=changes::true"

    - name: Get current date
      if: steps.changes.outputs.changes == 'true'
      id: date
      run: echo "::set-output name=date::$(date +'%d_%m_%Y')"

    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        branch: "update/${{ steps.date.outputs.date }}"
        labels: dependencies
        delete-branch: true
        commit-message: "Update packages"
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        assignees: alex289
        reviewers: alex289
        title: "Automatic Package Update ${{ steps.date.outputs.date }}"
        body: |
            This pull request includes updates to the packages in the solution.

            **Package Updates:**
            ```
            ${{ steps.outdated.outputs.updates }}
            ```
